# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce1f8b16e09839d407e26216f49bae99db052d8cdcccc0ee5d0fd146e4ae02de479af6a274ad695db0e82fce05607fa6da12e8c96ef26f3b65d3feea2b4af186

test:
  secret_key_base: 564d73050c87b9275d5d6969ac9eac68a5a0001ce99da03b8561a4071bcbbf9d8cd887d0b49a31fbe0a4b1338e9b4bbea07f4746cde60f321011cddba9d09845

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
